In [1]:
import torch
import torch.nn as nn
import torchvision
from torchvision import transforms
from torch.utils import data

d:\dev\anaconda3\envs\torch_cpu\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
net = nn.Sequential(nn.Flatten(),
                    nn.Linear(784, 256),
                    nn.ReLU(),
                    nn.Linear(256, 10))

In [2]:
batch_size, lr, epochs = 256, 0.1, 10

In [5]:
criterion = nn.CrossEntropyLoss(reduction=None)

In [3]:
trans = transforms.ToTensor()
mnist_train = torchvision.datasets.FashionMNIST(
    root="../mydata", train=True, transform=trans, download=True)
mnist_test = torchvision.datasets.FashionMNIST(
    root="../mydata", train=False, transform=trans, download=True)

In [4]:
train_iter = data.DataLoader(mnist_train, batch_size, shuffle=True)
test_iter = data.DataLoader(mnist_test, batch_size, shuffle=False)

In [8]:
res = [(net(X), y) for X, y in train_iter]

In [37]:
for outputs, y in res:
    print(outputs, y.shape[0])
    break

tensor([[-0.0172, -0.1390, -0.0038,  ...,  0.0056,  0.1393, -0.1045],
        [-0.0758, -0.0598,  0.0460,  ...,  0.0699,  0.1548,  0.0751],
        [ 0.0254, -0.0659, -0.0644,  ...,  0.0035,  0.1304, -0.1124],
        ...,
        [-0.0258, -0.1586,  0.1876,  ...,  0.0951,  0.0152,  0.0198],
        [-0.2097, -0.0152,  0.0391,  ...,  0.1437,  0.2652,  0.0164],
        [-0.0595, -0.0971,  0.1420,  ...,  0.0356,  0.0658,  0.0156]],
       grad_fn=<AddmmBackward0>) 256


In [14]:
outputs = []
Y = []
for X, y in test_iter:
    # for x in X:
    #     print(x.shape)
    output = net(X)
    outputs.append(output)
    print(output.shape)
    Y.append(y)
    # break

torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([256, 10])
torch.Size([16, 10])


In [43]:
new_outputs = torch.concat(outputs)

In [42]:
new_Y = torch.concat(Y)

In [46]:
torch.sum(new_outputs.argmax(dim=1) == new_Y) / new_Y.shape[0]

tensor(0.0291)

In [38]:
zip_data = tuple(zip(torch.concat(outputs), torch.concat(Y)))

In [40]:
for o, y in zip_data:
    print(o, y)
    break

tensor([-0.0247, -0.0041,  0.0811, -0.0551, -0.0524,  0.0121,  0.0898,  0.0439,
         0.0565, -0.0940], grad_fn=<UnbindBackward0>) tensor(9)


In [27]:
from itertools import chain
chain_data = chain(torch.concat(outputs), torch.concat(Y))

In [29]:
for d in chain_data:
    print(type(d))
    print(d)
    break

<class 'torch.Tensor'>
tensor([ 0.1147, -0.1640,  0.0676, -0.1565, -0.2467,  0.0928, -0.0969,  0.1913,
         0.1091,  0.1223], grad_fn=<UnbindBackward0>)


In [27]:
for data in mnist_train:
    print(type(data))
    print(data[0].shape, data[1])
    break

<class 'tuple'>
torch.Size([1, 28, 28]) 9


In [35]:
for X, y in train_iter:
    print(X.shape, y.shape)
    break

torch.Size([256, 1, 28, 28]) torch.Size([256])


In [24]:
for batch_idx, (X, y) in enumerate(train_iter):
    print(batch_idx, X.shape, y.shape)
    break

0 torch.Size([256, 1, 28, 28]) torch.Size([256])


In [ ]:
optimer = torch.optim.SGD(net.parameters(), lr=lr)

In [47]:
my_dict = {'a': 10, 'b': 5}
print(f'mydict={my_dict}')

mydict={'a': 10, 'b': 5}
